### ISSUE TITLE
Is there any pipeline to construct TE consensus sequences?

### ISSUE THREAD

**Issue by YTLogos** [cstritt/detettore#1]
I think TE consensus sequences is very important to detect TIP in population.

**Comment by cstritt** [comment]
Dear YTLogos, 
Sorry for the late answer. I don't think there is a ready-to-use pipeline to get consensus sequences from annotated copies. Did you take a look at the REPET package (Flutre et al. 2011)?  They compared different TE clustering algorithms, maybe you find some inspiration there.

**Comment by YTLogos** [comment]
Thanks. I will check it!
